version: '3'

volumes:
  authorization-base-data: {}
  sms-code-base-data: {}
  rehearsal-base-data: {}

services:
  config-server:
    build:
      context: ./config_server
      dockerfile: Dockerfile
    container_name: rb-config-server
    ports:
      - "4000:4000"
    networks:
      - rbnetwork

  service-discovery:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    container_name: rb-service-discovery
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: config-server:4000
    depends_on:
      - config-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - rbnetwork

  authorization-server-database:
    image: postgres
    container_name: authorization-server-database
    restart: always
    ports:
      - "54320:5432"
    env_file:
      - ./authorization_server/auth_server_db.env # configure postgres
    volumes:
      - authorization-base-data:/var/lib/postgresql/authorization_base_data
    networks:
      - rbnetwork

  authorization-server:
    build:
      context: ./authorization_server
      dockerfile: Dockerfile
    container_name: rb-authorization-server
    environment:
      PORT: 8090
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      DB_HOST: authorization-server-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: authorization-server-database:5432, service-discovery:8761
    depends_on:
      - config-server
      - service-discovery
      - authorization-server-database
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - rbnetwork

  sms-service-database:
    image: postgres
    container_name: sms-service-database
    restart: always
    ports:
      - "5431:5432"
    env_file:
      - ./sms_service/sms_service_db.env # configure postgres
    volumes:
      - sms-code-base-data:/var/lib/postgresql/sms_code_base_data
    networks:
      - rbnetwork

  sms-service:
    build:
      context: ./sms_service
      dockerfile: Dockerfile
    container_name: rb-sms-service
    env_file:
      - ./sms_service/sms_service_app.env
    environment:
      PORT: 8085
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      DB_HOST: sms-service-database
      DB_PORT: 5432
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: sms-service-database:5432, service-discovery:8761
    depends_on:
      - config-server
      - service-discovery
      - sms-service-database
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - rbnetwork

  rehearsal-database:
    image: postgres
    container_name: rehearsal-database
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./rehearsal_service/rehearsal_service_db.env # configure postgres
    volumes:
      - rehearsal-base-data:/var/lib/postgresql/rehearsal_base_data
    networks:
      - rbnetwork

  rehearsal-service:
    build:
      context: ./rehearsal_service
      dockerfile: Dockerfile
    container_name: rb-rehearsal-service
    env_file:
      - ./rehearsal_service/rehearsal_service_app.env
    environment:
      PORT: 8888
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      DB_HOST: rehearsal-database
      DB_PORT: 5432
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: rehearsal-database:5432, service-discovery:8761
    depends_on:
      - config-server
      - service-discovery
      - rehearsal-database
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - rbnetwork

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: rb-gateway
    env_file:
      - ./gateway/gateway_app.env
    environment:
      PORT: 8080
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      AUTH_SERVER_HOST: authorization-server
      AUTH_SERVER_PORT: 8090
      REHEARSAL_SERVICE_HOST: rehearsal-service
      REHEARSAL_SERVICE_PORT: 8888
      SMS_SERVICE_HOST: sms-service
      SMS_SERVICE_PORT: 8085
      WAIT_HOSTS: config-server:4000, service-discovery:8761, authorization-server:8090, rehearsal-service:8888, sms-service:8085
    depends_on:
      - config-server
      - service-discovery
      - authorization-server
      - rehearsal-service
      - sms-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - rbnetwork

networks:
  rbnetwork:
    driver: bridge