version: '3'
services:
  config-server:
    build:
      context: ./config_server
      dockerfile: Dockerfile
    container_name: rb-config-server
    ports:
      - "4000:4000"
#      volumes:
#        - "/tao-elszamolas/logs:/var/log/tao-elszamolas"
    networks:
      - rbnetwork

  service-discovery:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    container_name: rb-service-discovery
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: config-server:4000
    depends_on:
      - config-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - rbnetwork

  authorization-server-database:
    image: postgres
    container_name: authorization-server-database
    restart: always
    ports:
      - "54320:5432"
    env_file:
      - database.env # configure postgres
    networks:
      - rbnetwork

  authorization-server:
    build:
      context: ./authorization_server
      dockerfile: Dockerfile
    container_name: rb-authorization-server
    environment:
      PORT: 8090
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      DB_HOST: authorization-server-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: authorization-server-database:5432, service-discovery:8761
    depends_on:
      - config-server
      - service-discovery
      - authorization-server-database
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - rbnetwork

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: rb-gateway
    environment:
      PORT: 8080
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 4000
      SERVICE_DISCOVERY_HOST: service-discovery
      SERVICE_DISCOVERY_PORT: 8761
      WAIT_HOSTS: config-server:4000, service-discovery:8761, authorization-server:8090
    depends_on:
      - config-server
      - service-discovery
      - authorization-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - rbnetwork

networks:
  rbnetwork:
    driver: bridge