spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rehearsal_base
    username: postgres
    password: testpassword
    driverClassName: org.postgresql.Driver
    initialization-mode: always