spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rehearsal_base
    username: postgres
    password: testpassword
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
rehearsal:
  canBeCancelledBefore: 24 #hours
timetable:
  start: 9 #hours
  end: 24 #hours
  period: 7 #days
smsCode:
  waitingInterval: 60 #seconds
  countRequestsInterval: 300 #seconds
  requestsNumber: 3
